### ISSUE TITLE
UI - Markdown rendering

### ISSUE THREAD

**Issue by peperunas** [enricoros/nextjs-chatgpt-app#11]
As the title says, support Markdown in the bot's output.

**Comment by enricoros** [comment]
You have AMAZING ideas! After a quick look, we can use rendering libraries like react-markdown in place of the Prism Code Blocks in the application. Easy change, the hard part is to auto-detect if it's Markdown.

I'm thinking of a combo of Auto-detect + Markdown User Switch in code blocks - that should cover it. Unless the markdown is not in a code block "```" but it's within a text block.

**Comment by enricoros** [comment]
Hi @peperunas, can you give me an example query (or screenshot) of the use case where you'd like to render markdown?

Right now, the code blocks within markdown are rendered as code. And there is syntax highlighting (color) for '.md' files. But it's not rendered - and will be complex to interleave Markdown and code-blocks render. If you send me a screenshot of what you'd like to be rendered as Markdown (vs. syntax highlighted) it would help 🙏

**Comment by centminmod** [comment]
Markdown would be nice. For me, a simple case is where I have CSV formatted data and I ask ChatGPT to convert to Markdown table format, it just creates the actual Markdown rendered table which isn't what I want. I wanted the Markdown code itself. So not sure if that is just my lack of imagination for prompt instruction or something that you can improve on in your app?

**Comment by enricoros** [comment]
If you want the markdown code, that's the default output: I mean the following:
![image](https://user-images.githubusercontent.com/32999/227496229-2ad89dfa-d6b3-4476-882a-333877a8be03.png)
If you want it to be rendered as table, then I need to implement the grid renderer. But seems like you want the code, aka the way it is now?

**Comment by centminmod** [comment]
I see looks like your app differs from chatgpt, chatgpt would render it as a table for 2nd example.

**Comment by enricoros** [comment]
> Now that I read your comment, it came to me it would be great to have a "switch" button allowing the user to see the rendered Markdown and the sources. What do you think?

Good idea - I have a half-baked implementation, so haven't landed this yet

**Comment by enricoros** [comment]
This feature mostly works, but needs some style cleanup (spacing can get weird).  An UI option chooses between rendering of the source code (raw model output) and of the markdown.

**Comment by enricoros** [comment]
Pixel perfection Markdown rendering, tables included.

This:
![image](https://user-images.githubusercontent.com/32999/230601755-f11bea85-613b-4a4d-9641-040bc51a19f5.png)

Becomes this:
![image](https://user-images.githubusercontent.com/32999/230601864-0bb48b98-bd12-420d-a010-f80d880b5287.png)

And in perfect dark mode too:
![image](https://user-images.githubusercontent.com/32999/230604649-8201753d-5b03-47b4-93e3-828ab4b4ddd4.png)

Github-flavored markdown included, and cooler looks (font, line-height) compared to GitHub.
