### ISSUE TITLE
Context utilization UI & UX (8k, 4k, ..)

### ISSUE THREAD

**Issue by enricoros** [enricoros/nextjs-chatgpt-app#13]
Measure the token usage of a chat, to know when we're about to hit the limit, and offer ways to deal with it.

UX could be a progress bar with utilization and remaining capacity when composing a new message. A red bar would hint at removing some older chat messages before being able to compose a new message. An alternative would be to automatically prune messages from the start of the conversation (but keeping the system message).

Tech note: context windows vary by Model - GPT-4 8k having the largest until the 32k comes along.

Note: originally mentioned by by @bytesuji in https://github.com/enricoros/nextjs-chatgpt-app/issues/2#issuecomment-1475641938_

**Comment by enricoros** [comment]
Related to #17

**Comment by centminmod** [comment]
It would be nice if each message input and output had a check box next to them. So when we hit the limit of a context, we can bulk check box selectively choose messages for deletion :)

**Comment by enricoros** [comment]
I can do this :)

**Comment by enricoros** [comment]
Landed some code yesterday that shows the token usage on the send box only. Close to have this working across the board.

As I look into this, it's interesting to notice that there are 2 use cases that are related to token counting. One is to know the expense of tokens. The other, how many tokens are left before the model pushes back and does not execute your request.

Thinking on whether to display the used tokens, or remaining tokens.

**Comment by jondwillis** [comment]
> Landed some code yesterday that shows the token usage on the send box only. Close to have this working across the board.
> 
> As I look into this, it's interesting to notice that there are 2 use cases that are related to token counting. One is to know the expense of tokens. The other, how many tokens are left before the model pushes back and does not execute your request.
> 
> Thinking on whether to display the used tokens, or remaining tokens.

Interested in this, is it merged already? commits?

Wondering if you used https://github.com/openai/tiktoken

**Comment by enricoros** [comment]
> Wondering if you used https://github.com/openai/tiktoken

Yes, that's what we're using for
![image](https://user-images.githubusercontent.com/32999/230335514-2763fd7c-3c29-48c7-80fe-3d8d2e227b46.png)
the indicator above :)

**Comment by enricoros** [comment]
It's getting there, but I need to add its usage in more places, so the full conversation's token are estimated and not just the one we're composing. But yeah, almost there :)

**Comment by enricoros** [comment]
I've improved the estimated token usage. In particular, found that the tokens are 3 + sum_messages(4 + token_message).

Now the UI is using it, in a few places - can be cleaned up, but the forecasts are very much in line.

Sometimes there's still discrepancy, and I believe that's due to the token library.

**Comment by enricoros** [comment]
Done in https://github.com/enricoros/nextjs-chatgpt-app/commit/17f4334e45d65030cf711f024090a17e98ada9e1

what was done: 
 - token counting of messages and the composer
 - algo to sum up the conversation
 - indirect (history & response) vs 'direct' (message being composed)
 - per-model limit
 - badge to warn about overflow

what could still be done:
- "cleanup" mode to select and discard old messages
- sliding window approach #76 -- which is a sort of heuristics-based cleanup
