### ISSUE TITLE
Multiple chats & local history - conversation sidebar

### ISSUE THREAD

**Issue by enricoros** [enricoros/nextjs-chatgpt-app#14]
ChatGPT-like conversations sidebar to have multiple chats - locally stored on localstorage/indexedDB in your browser. This will make conversations instantly resumeable and reusable.

Can have a transparent UX via left-side hamburger menu, and enable other features such as clearing the conversation, 'forking' a conversation, etc.

_Originally posted by @bytesuji in https://github.com/enricoros/nextjs-chatgpt-app/issues/2#issuecomment-1475641938_

**Comment by enricoros** [comment]
Are there storage solutions which are "bring your API key", so it can be as simple as with the OpenAI API?

If yes, I'd love to have that, and the user could just enter the API key to one of their buckets, and the UI will sync. Please let me know if you know more about this.

**Comment by centminmod** [comment]
With most S3 compatible storage providers, it is just providing such a key though it's usually the KEY + Secret key i.e. for using AWS CLI tool with various S3 providers https://awscli-get.centminmod.com/. Most common I'd accommodate for would AWS S3, DigitalOcean, Linode, Backblaze, and Cloudflare R2. I think most users you'd be targeting your app for would be folks who already use one of these in some form already 😃 

I am not that familiar with Node.js but AWS also have examples like https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/s3-node-examples.html and https://www.npmjs.com/package/s3-node

Cloudflare R2 S3 compatible storage also have examples https://developers.cloudflare.com/r2/examples/aws/

There's probably already some ready mode S3 library for your stack I'd imagine that you can integrate ?

**Comment by enricoros** [comment]
Closed with https://github.com/enricoros/nextjs-chatgpt-app/commit/db6ce57dc0ba149e278ea239d6f27e273208635e 

![image](https://user-images.githubusercontent.com/32999/230886011-1805a0de-4e87-487e-877b-1bd5d05ffb5a.png)

Long awaited. Super useful. @centminmod here you go.

For more extensions of this feature (e.g. Titles) - please open new tickets.
