### ISSUE TITLE
GPT -4 Error

### ISSUE THREAD

**Issue by jogun22** [enricoros/nextjs-chatgpt-app#16]
when im using the Gpt 4 models the error always occours the error message 
OpenAI API error: 404 Not Found {"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by enricoros** [comment]
Hi, this means your API key is not enabled for 'gpt-4' yet. Can you confirm you have been invited to the gpt-4 preview API already?
