### ISSUE TITLE
Error: the model `gpt-4` does not exist

### ISSUE THREAD

**Issue by HunteRoi** [enricoros/nextjs-chatgpt-app#18]
## Context

I have an issue while using your demo app. It seems like the "gpt-4" modal does not exist when asking for some answers from the chat app. Could you look into it please?

## Steps to reproduce

1. open https://nextjs-chatgpt-app-enricoros.vercel.app/
2. create an api key on openai.com
3. feed it to the nextjs-chatgpt-app
4. choose "Developer" in the dropdown
5. ask the chat to give you the code for a pacman game (could be anything else TBH)

## Result

![image](https://user-images.githubusercontent.com/32441291/226677989-6c52da89-9736-466f-b579-0b74a468cadb.png)

## Intended result

A valid answer from GPT-4 written in the chat.

**Comment by enricoros** [comment]
Screenshot of the new error UI. Also used to explain Error 429 (systems busy).

![image](https://user-images.githubusercontent.com/32999/226814808-5bd24b8f-6d10-459f-9215-d15080d514fb.png)
