### ISSUE TITLE
Code run html

### ISSUE THREAD

**Issue by rossman22590** [enricoros/nextjs-chatgpt-app#19]
when i click the run button i get a bunch of errors, in the little sections running the code. how can i fix the code sandbox

sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQVEsSUFBSSxDQUFBO0FBQUMsUUFBUSxHQUFDLEdBQUcsQ0FBQTtBQUFDLEdBQUcsR0FBQyxRQUFRLENBQUEiLCJzb3VyY2VzQ29udGVudCI6WyI8YnV0dG9uIHR5cGU9XCJidXR0b25cIj5CdXkgTm93PC9idXR0b24+Il19'
    at https://2-1-9-sandpack.codesandbox.io/static/js/sandbox.d52cf7871.js:1:258176
    at e.value (https://2-1-9-sandpack.codesandbox.io/static/js/sandbox.d52cf7871.js:1:258295)
    at e.value (https://2-1-9-sandpack.codesandbox.io/static/js/sandbox.d52cf7871.js:1:256570)
    at Worker.<anonymous> (https://2-1-9-sandpack.codesandbox.io/static/js/sandbox.d52cf7871.js:1:257164)"

**Comment by rossman22590** [comment]
/index.js: Cannot set properties of null (setting 'innerHTML') (3:0)

  1 | import "./styles.css";
  2 | 
> 3 | document.getElementById("app").innerHTML = `
      ^
  4 | <h1>Hello world</h1>
  5 | `;
  6 |

**Comment by enricoros** [comment]
Thanks for reporting - do you have an example of the code that's trying to run. The heuristics to detect code and send it to the Sandpack execution engine are weak/cheap now.

This is the function that's configuring Sandpack for running HTML code:
https://github.com/enricoros/nextjs-chatgpt-app/blob/3e6bbd8fe86f23d640f9bb56e82dd97e00f90608/components/ChatMessage.tsx#L105

**Comment by rossman22590** [comment]
like super basic buy button in html :) does it not run basic code?

**Comment by enricoros** [comment]
Done, let me know if you have any issues with the resolution.

**Comment by rossman22590** [comment]
is this feature removed?
