### ISSUE TITLE
Feature: export chats

### ISSUE THREAD

**Issue by centminmod** [enricoros/nextjs-chatgpt-app#25]
Something I wished for in official ChatGPT is the ability to save and export chat sessions. i.e. format preserved HTML files or have a check box against each input/output message, and we can bulk select which messages to save to HTML files.

Guess it would be related to https://github.com/enricoros/nextjs-chatgpt-app/issues/14. If you had S3 storage support, could also save chat conversations to S3 storage and have ability to recall them from S3 storage for view/review in your app - maybe loaded into the scratch pad notes https://github.com/enricoros/nextjs-chatgpt-app/issues/17 ? :)

**Comment by enricoros** [comment]
@centminmod: this is implemented and looks quite great. And it's still done with privacy/anonymity.
This is perfect to share with friends and loved ones.

Links will be live on paste.gg, unlisted, expire in 30 days, and have a 1-time 'deletion key', which one can use to take down the post before expiration.

Export:
![image](https://user-images.githubusercontent.com/32999/229286901-6a0c69fa-786a-45cd-b6f8-01b688c3873b.png)

Confirmation:
![image](https://user-images.githubusercontent.com/32999/229287237-28ab44dc-1145-47be-9929-40cf32dd487c.png)

Conversation:
LINK: https://paste.gg/c8b3b9c7f62b4e7ead481715c20ed947 
![image](https://user-images.githubusercontent.com/32999/229287671-8dae2fb3-180a-49c7-b5fa-cc350fc5842d.png)

**Comment by centminmod** [comment]
@enricoros sweet looks awesome 👍

**Comment by enricoros** [comment]
Try it out, it's actually really cool looking on the scrollable markdown page.
