### ISSUE TITLE
Vercel's Analytics component must be used out of CacheProvider

### ISSUE THREAD

**Issue by feenn** [enricoros/nextjs-chatgpt-app#28]
Currently the Analytics component is placed inside the CacheProvider. As a result, the [Audiences] https://vercel.com/feenn/chatgpt-app-nextjs/analytics/audience) keeps waiting for data all the time until I redeploy the code by placing the Analytics component next to the CacheProvider and wrapping with a fragment. So wired!

**Comment by enricoros** [comment]
Hi @feenn, thanks for debugging this. I've moved the code as you said. Works for me, but can you confirm it's working for your as well?

**Comment by feenn** [comment]
> Hi @feenn, thanks for debugging this. I've moved the code as you said. Works for me, but can you confirm it's working for your as well?

Works for me too. That's Great :)

**Comment by enricoros** [comment]
> > Hi @feenn, thanks for debugging this. I've moved the code as you said. Works for me, but can you confirm it's working for your as well?
> 
> Works for me too. That's Great :)

Awesome! Let me know of new features you'd like. Significant update just pushed.
