### ISSUE TITLE
Feature - Clear chat

### ISSUE THREAD

**Issue by peperunas** [enricoros/nextjs-chatgpt-app#3]
It would be nice to have a button to reset the chat, thus starting a new session.

**Comment by enricoros** [comment]
For now it's hidden, it's a double click on the "GPT-4" title :)
Good point, should be there! I'll add.

**Comment by peperunas** [comment]
Thank you 😄

**Comment by enricoros** [comment]
Done! And in a proper way. Now chats are persisted in the browser, and there is support for multi-chats.

Menu Item:
![image](https://user-images.githubusercontent.com/32999/228523735-1af6b5c4-3e33-4243-873f-c3e250bfd390.png)

Confirmation
![image](https://user-images.githubusercontent.com/32999/228523784-cec12bbb-763e-4cef-a8e1-cc08550f47e0.png)
