### ISSUE TITLE
ligatures in code

### ISSUE THREAD

**Issue by harlanlewis** [enricoros/nextjs-chatgpt-app#33]
Loving the incredible progress on this repo!

Are you open to removing [jetbrains mono ligatures](https://www.jetbrains.com/lp/mono/#ligatures) in code blocks? Heavily subjective opinion - I appreciate the legibility they add in sentence form, but find the transformation of `!=`, `>=`, `=>` etc quite distracting. The non-transformative (ie just whitespace balancing) of `[||]` etc is fine.

Should this be done with a font-family switch, or CSS `font-variant-ligatures`?

**Comment by enricoros** [comment]
Thanks Harlan - the code is at a good stage when now the fun can begin, and we can seriously experiment with bigger things. Feels like the scaffolding is done (I will enable multi-chats soon, I just need to test that the IDs are stable and there's not too much re-rendering).

You make a valid point about the ligatures - in code, it's distracting. I don't know how to implement it, but if you submit a patch that disables them in CodeBlocks I'll merge it right away! Feel free to choose the approach that you think works best, whether it's a font-family switch or CSS font-variant-ligatures (I don't know much of it)

I think we should keep them in TextBlocks (sentence form), as people like more 'markdown-ish' rendering on the Text parts.
