### ISSUE TITLE
Support fullscreen on web?

### ISSUE THREAD

**Issue by Ssiswent** [enricoros/nextjs-chatgpt-app#38]
Not fullscreen in chrome.
![image](https://user-images.githubusercontent.com/37449310/229004974-3ce11590-3593-4da5-bb9e-6d1f294fb765.png)

**Comment by enricoros** [comment]
Wait, have you tried this option **Wide Mode**: 

![image](https://user-images.githubusercontent.com/32999/229012500-33af4aa2-f5e3-4ec3-961c-39418025f05f.png)

**Comment by enricoros** [comment]
Asking for more details on this. Will close within 2 days otherwise.

**Comment by enricoros** [comment]
@Ssiswent , please update, otherwise I consider this closed.

**Comment by Ssiswent** [comment]
> Wait, have you tried this option **Wide Mode**:
> 
> ![image](https://user-images.githubusercontent.com/32999/229012566-62f3198e-214e-4ac1-89b1-578679a14048.png)

Wow, Thanks a lot!
