### ISSUE TITLE
Feature - User defined task list

### ISSUE THREAD

**Issue by peperunas** [enricoros/nextjs-chatgpt-app#4]
Defining tasks and saving them in the browser's storage would be great. In a way, expand on the already existing "developer", "scientist" and so on.

**Comment by enricoros** [comment]
Good idea! There's a PR now, #7 , does this add the feature you think, or are you seeing a broader scope / idea for this?

**Comment by peperunas** [comment]
That's what I meant, yes. :-) 

In the future it would be great to save multiple custom system messages

**Comment by enricoros** [comment]
I think would be also good to capture "Tasks" as "repetitive workflows" that one does, or prompt templates maybe. So they can quickly be reused without typing. Wdyt?

**Comment by peperunas** [comment]
Spot on 😁

**Comment by enricoros** [comment]
Closing as duplicate of #35
