### ISSUE TITLE
Suggestion: Sans font for text, Mono for code

### ISSUE THREAD

**Issue by typpo** [enricoros/nextjs-chatgpt-app#44]
Hello,

I've modified my client so that the assistant uses the same font as the user for prose, mono for code.

![image](https://user-images.githubusercontent.com/310310/229327607-1076a7e2-3208-4695-abf6-5a149b4c0d6b.png)

Curious if you think this is desired.  I think it enhances readability.  If you'd like to keep assistant text fully mono, would you be open to a PR that adds a toggle?

**Comment by peperunas** [comment]
Looks better with the two different fonts - they are easier on the eyes

**Comment by rossman22590** [comment]
I agree!

**Comment by enricoros** [comment]
Agreed, @typpo, @peperunas, @rossman22590. I've applied the change!
