### ISSUE TITLE
UX - Increase chat bubbles' horizontal margin

### ISSUE THREAD

**Issue by peperunas** [enricoros/nextjs-chatgpt-app#5]
I find centered chat views a better choice as they are more user-friendly and easier to read. 

Having whitespace on both sides helps users focus on the conversation without feeling overwhelmed. Consistent line length is also maintained, making it easier to follow what's being said.

Is that something worth considering, @enricoros?

Thanks!

**Comment by enricoros** [comment]
For sure. Layout is responsive right now, and wanted to keep it minimal and clean, but likely people are using this on desktop as while developing or working, so more space would make sense.

Are you able to take a screenshot and draw arrows to where you want the changes to be?

**Comment by peperunas** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/6033387/226387363-0f28cb3d-f71e-499f-bae1-72fa1a8ac807.png">

**Comment by enricoros** [comment]
Added a "Wide mode" setting to toggle between centered/wide. However the default for wide is the "xl" preset (which is above 1200px I believe).

![image](https://user-images.githubusercontent.com/32999/228524165-e9d60ba1-6632-4e9a-b9f9-81319b2f71b0.png)

Not sure whether I should reduce the non-wide (centered) mode to 'lg' instead.

**Comment by enricoros** [comment]
Unless I hear otherwise, the "Wide mode" fixes this issue.
Related to #38 (it's the actual opposite)

**Comment by peperunas** [comment]
The wide mode toggle does not change the web app's appearance for me on an M1 Pro 14" Macbook Pro.

**Comment by enricoros** [comment]
I see. It seems like you're already full screen, so toggling that switch doesn't make any difference, correct?

I can easily change it to add more whitespace for you (there's a Container with 'xl" to be changed to 'lg') but then everyone that's on a larger screen will have lots and lots of whitespace. Ideas?

**Comment by enricoros** [comment]
Fixed this finally.

Appearance:
![image](https://user-images.githubusercontent.com/32999/229962976-71957609-e568-4647-9b0f-f45c2fb4877a.png)

Size selector inside "Settings"
![image](https://user-images.githubusercontent.com/32999/229963074-71f4c2ca-6a2c-462a-a3a9-00f645b3f793.png)

@peperunas let me know if you are using this project, or what other features you'd like

**Comment by peperunas** [comment]
@enricoros, thank you for your work. Definitely, this is my go-to WebUI :-)

**Comment by enricoros** [comment]
@peperunas well you better 😁 not that we have this amazing margin 😁😁
I want to know more features that would make your life 10x easier, if any.
