### ISSUE TITLE
increase size the chat overview

### ISSUE THREAD

**Issue by seven4x** [enricoros/nextjs-chatgpt-app#54]
The preview text length is too small to distinguish between sessions
![image](https://user-images.githubusercontent.com/1982168/229750871-51a429bd-6052-4c54-ac2c-3e29ced3a2c9.png)

**Comment by enricoros** [comment]
Hello @seven4x and welcome. I don't know where that is from, but it's the wrong project.

Check out our project, there's a public demo link on the home.  There are quite a few advanced features, such as import of PDFs, token counters, voice input, drag & drop code, markdown and syntax highlight, and a typing gif :)

**Comment by seven4x** [comment]
![image](https://user-images.githubusercontent.com/1982168/230104569-b5962b53-24c6-4e85-8ebc-378d2734e400.png)
@enricoros Sorry, I recreate the snapshot. we can see that only can show 3~4 words on the left.

**Comment by enricoros** [comment]
@seven4x this is the wrong project :) you should try out our chat instead. Looks gorgeous :)
