### ISSUE TITLE
The wide mode disappeared

### ISSUE THREAD

**Issue by Ssiswent** [enricoros/nextjs-chatgpt-app#71]
Is there anyway I make it fullscreen?
Thanks.
<img width="547" alt="image" src="https://user-images.githubusercontent.com/37449310/230906291-f05b3918-20f8-4db6-94e3-7e746452193e.png">

**Comment by enricoros** [comment]
@Ssiswent: had to move it to the Settings (as you figured out) because the UI is getting too cluttered
