### ISSUE TITLE
Feature request: use proxy environment variables (server and/or client side as needed)

### ISSUE THREAD

**Issue by epylar** [enricoros/nextjs-chatgpt-app#86]
I would like to be able to use this behind a proxy but it seems that the code does incorporate proxy support (I get a timeout when sending a message to GPT, when I'm behind a proxy).

**Comment by enricoros** [comment]
Is this similar to #26? Please see the discussion there too.

**Comment by epylar** [comment]
> Is this similar to #26? Please see the discussion there too.

Ah, I missed this. Thanks.
